data:
    image: busybox
    volumes: 
        - workspace:/data
db:
    image: percona
    restart: always
    volumes_from:
        - percona_data
    environment:
        - MYSQL_ROOT_PASSWORD=test
dbclient:
    image: percona
    command: bash
    volumes_from:
        - db
    links:
        - db
redis:
    image: redis
    restart: always
mailcatcher:
    image: schickling/mailcatcher
    restart: always
phpfpm:
    build: phpfpm
    restart: always
    volumes_from:
        - data
    links:
        - db
        - mailcatcher
        - redis
web:
    build: nginx
    restart: always
    volumes_from:
        - data
    links:
        - phpfpm:fpm
        - mailcatcher
    ports:
        - 80:80
        - 443:433

